name: Linter

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  # `eslint` static analyzer
  #
  # The package.json also has a format script built on `prettier`,
  # but that is already integrated into `eslint` and not invoked
  # separately here.
  run-eslint:
    name: Run eslint TypeScript Linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: 22.4.x

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Run Lint Script
        id: npm-lint
        run: npm run lint
